authors = ["fpacaud <francoispacaud8@gmail.com>"]
name = "CUSOLVERRF"
uuid = "a8cc9031-bad2-4722-94f5-40deabb4245c"
version = "0.2.2"

[compat]
CUDA = "4.0"
KLU = "0.3, 0.4"
julia = "1.6"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
KLU = "ef3ab10e-7fda-4108-b977-705223b18434"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
