name = "CUSOLVERRF"
uuid = "a8cc9031-bad2-4722-94f5-40deabb4245c"
authors = ["fpacaud <francoispacaud8@gmail.com>"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
KLU = "ef3ab10e-7fda-4108-b977-705223b18434"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CEnum = "0.4"
CUDA = "4.0"
KLU = "0.3"
julia = "1.6"
